feat: Add category create, get all, get single, and delete
squirrelwine/catalog-api pull request #3
Opened 2022-02-07 12:37 UTC by squirrelwine

2022-02-09 02:00 UTC, ke-np requested changes
Also, please make use of async APIs for SQLAlchemy.

2022-02-09 02:00 UTC, ke-np commented on main/api/routes/category.py
> +async def get_single_category(category_id, session: Session = Depends(get_db_session)):
Typing for `category_id`?

2022-02-09 02:00 UTC, ke-np commented on main/api/routes/category.py
> +        )
Let's move this into a dependency so we can easily reuse it.

2022-02-09 02:00 UTC, ke-np commented on main/api/routes/category.py
> +        )
Move this into a dependency. We will need this check for other APIs soon.

2022-02-09 02:00 UTC, ke-np commented on main/api/routes/category.py
> +        )
This should be a dependency too.

2022-02-09 02:00 UTC, ke-np commented on main/schemas/category.py
> +        return name_string
Why don't we do `name: constr(min_length=1, max_length=50)`?

2022-02-09 02:00 UTC, ke-np commented on main/schemas/category.py
> +        orm_mode = True
Let's have a base class for this as we're gonna reuse it for item schemas as well.

2022-02-09 02:00 UTC, ke-np commented on main/services/database/category_crud.py
> +from typing import List
`main/services/category.py` is good enough. What convention are you following here?

2022-02-09 02:00 UTC, ke-np commented on main/services/database/category_crud.py
> +    return category
There is a better API to get a record using its primary key. Please research & use that one instead.

2022-02-09 02:00 UTC, ke-np commented on main/services/database/category_crud.py
> +def get_category_by_id(session: Session, category_id: str) -> Category:
Return typing should be `Optional[Category]`.

2022-02-09 02:00 UTC, ke-np commented on main/services/database/category_crud.py
> +def get_categories(session: Session) -> List[CategoryBatchResponseSchema]:
Why not `List[Category]`?

2022-02-09 02:00 UTC, ke-np commented on main/services/database/category_crud.py
> +    session.commit()
Missing typing for name & description. This function is not well-designed, it should return the created category.

2022-02-09 02:00 UTC, ke-np commented on main/services/database/category_crud.py
> +    session.commit()
It's better to support deleting a record using its ID.

2022-02-11 05:29 UTC, duong-le requested changes

2022-02-11 05:29 UTC, duong-le commented on main/api/dependencies/auth.py
> +        payload = jwt.decode(token, settings.JWT_SECRET_KEY, settings.JWT_ALGORITHM)
Create a function in `auth` service for decoding token

2022-02-11 05:29 UTC, duong-le commented on main/api/dependencies/auth.py
> +        )
Custom exception

2022-02-11 05:29 UTC, duong-le commented on main/api/dependencies/category.py
> +        )
Should this be not found exception? Additionally, create a reusable not found exception.

2022-02-11 05:29 UTC, duong-le commented on main/api/routes/category.py
> +        )
Custom exception

2022-02-14 03:09 UTC, duong-le commented on main/services/category.py
> +        raise NoEntityException
`NoEntityException` or `NoEntityException()`?

2022-02-14 04:31 UTC, duong-le approved these changes

2022-02-14 04:31 UTC, merged